remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-paginate

title: "nawoong"

description: "nawoong.log"

paginate: 15
paginate_path: "/page/:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
